# Generated by Django 5.1.4 on 2024-12-26 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state_province', models.CharField(max_length=50)),
                ('education_level', models.CharField(max_length=100)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('skills', models.TextField()),
                ('languages_spoken', models.TextField()),
                ('work_availability', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('freelance', 'Freelance')], max_length=15)),
                ('work_schedule_preference', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('flexible', 'Flexible')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
