# Generated by Django 5.1.4 on 2025-04-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='min_clock_cycles',
            field=models.PositiveIntegerField(default=1, help_text='Number of clock-in/out cycles required per worker before task can be completed'),
        ),
    ]
