# Generated by Django 5.1.4 on 2024-12-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
