# Generated by Django 5.1.4 on 2024-12-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
