# Generated by Django 5.1.4 on 2025-04-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_badge_reward_pointstransaction_userpoints_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='related_feedback',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
