# Generated by Django 5.1.4 on 2025-04-10 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_reward_awarded_at_reward_awarded_to_reward_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('points_used', models.PositiveIntegerField()),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Task Reward Assignment',
                'verbose_name_plural': 'Task Reward Assignments',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['points_required']},
        ),
        migrations.AlterModelOptions(
            name='pointstransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['point_cost']},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-date_earned']},
        ),
        migrations.AlterModelOptions(
            name='userpoints',
            options={'verbose_name_plural': 'User points'},
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='awarded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='pointstransaction',
            name='related_feedback',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='awarded_to',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='task',
        ),
        migrations.AddField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='related_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='base.reward'),
        ),
        migrations.AddField(
            model_name='reward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='awarded_for_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to='base.task'),
        ),
        migrations.AddField(
            model_name='userpoints',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='base.task'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('adjust', 'Adjusted'), ('expire', 'Expired')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('bonus', 'Cash Bonus'), ('timeoff', 'Paid Time Off'), ('gift', 'Gift Card'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['user', 'timestamp'], name='base_points_user_id_e76af4_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['related_task'], name='base_points_related_e68cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['related_reward'], name='base_points_related_240187_idx'),
        ),
        migrations.AddField(
            model_name='taskreward',
            name='awarded_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rewards', to='base.reward'),
        ),
        migrations.AddField(
            model_name='taskreward',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rewards', to='base.task'),
        ),
    ]
