# Generated by Django 5.1.4 on 2025-04-10 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_taskreward_alter_badge_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskreward',
            name='awarded_to',
        ),
        migrations.RemoveField(
            model_name='taskreward',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='taskreward',
            name='task',
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pointstransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userpoints',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='pointstransaction',
            name='base_points_user_id_e76af4_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointstransaction',
            name='base_points_related_e68cfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointstransaction',
            name='base_points_related_240187_idx',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='created_at',
            new_name='awarded_at',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pointstransaction',
            name='related_reward',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='awarded_for_task',
        ),
        migrations.RemoveField(
            model_name='userpoints',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='related_feedback',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='awarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_rewards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reward',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='base.task'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.task'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('adjust', 'Adjusted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('bonus', 'Cash Bonus'), ('timeoff', 'Paid Time Off'), ('other', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TaskReward',
        ),
    ]
