# Generated by Django 5.1.4 on 2025-01-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_dashboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_availability',
            field=models.CharField(choices=[('fulltime', 'Fulltime'), ('parttime', 'Part-time'), ('freelance', 'Freelance')], max_length=15),
        ),
    ]
