# Generated by Django 5.1.4 on 2025-04-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_userpoints_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointstransaction',
            name='related_feedback',
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='related_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='base.reward'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='base.task'),
        ),
    ]
