# Generated by Django 5.1.4 on 2025-04-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_reward_eligible_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='awarded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='awarded_to',
        ),
        migrations.AddField(
            model_name='reward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
