# Generated by Django 5.1.4 on 2025-01-15 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_timelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='clock_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
