# Generated by Django 5.1.4 on 2025-01-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_timelog_clock_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('worker', 'Worker')], default='worker', max_length=10),
        ),
    ]
