# Generated by Django 5.1.4 on 2025-04-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_reward_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RewardRedemption',
        ),
    ]
