# Generated by Django 5.1.4 on 2025-01-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
