# Generated by Django 5.1.4 on 2025-04-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_completion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
