# Generated by Django 5.1.4 on 2025-04-16 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_task_estimated_completion_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_completion_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
