# Generated by Django 5.1.4 on 2025-04-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_task_estimated_completion_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='break_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
