# Generated by Django 5.1.4 on 2025-04-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_timelog_break_end_timelog_break_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='break_start',
        ),
    ]
