# Generated by Django 5.1.4 on 2025-02-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_managerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
    ]
