# Generated by Django 5.1.4 on 2025-04-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_timelog_break_end_remove_timelog_break_start'),
    ]

    operations = [
    # First alter the unique_together while fields still exist
    migrations.AlterUniqueTogether(
        name='userbadge',
        unique_together=set(),
    ),
    # Then remove fields and models
    migrations.RemoveField(
        model_name='userbadge',
        name='badge',
    ),
    migrations.RemoveField(
        model_name='userbadge',
        name='user',
    ),
    migrations.DeleteModel(
        name='Badge',
    ),
    migrations.DeleteModel(
        name='UserBadge',
    ),
]
    
