# Generated by Django 5.1.4 on 2025-03-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_userprofile_city_town_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.task'),
        ),
    ]
