# Generated by Django 5.1.4 on 2025-03-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_task_project_name_project_status_task_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('worker', 'Worker')], default='worker', max_length=50),
        ),
    ]
